[[themes]]
name = "pywal"

[themes.palette]
background = "#0c0c1b"
foreground = "#c2c2c6"
black = "#0c0c1b"
red = "#739793"
green = "#96A69E"
yellow = "#D2B49A"
blue = "#E7C5A1"
magenta = "#F5D7B2"
cyan = "#FAE2BD"
white = "#c2c2c6"
bright_black = "#5b5b6f"
bright_red = "#739793"
bright_green = "#96A69E"
bright_yellow = "#D2B49A"
bright_blue = "#E7C5A1"
bright_magenta = "#F5D7B2"
bright_cyan = "#FAE2BD"
bright_white = "#c2c2c6"
