# -------------------------
# STARSHIP CONFIG (pywal-aware)
# -------------------------

format = """
[](bg:${WAL_COLOR_0:-#444444})\
$os\
$username\
[](bg:${WAL_COLOR_0:-#444444} fg:${WAL_COLOR_7:-#888888})\
$directory\
[](bg:${WAL_COLOR_7:-#888888} fg:${WAL_COLOR_15:-#bbbbbb})\
$git_branch\
$git_status\
[](bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_16:-#dddddd})\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](bg:${WAL_COLOR_16:-#dddddd} fg:${WAL_COLOR_15:-#eeeeee})\
$docker_context\
[](bg:${WAL_COLOR_15:-#eeeeee} fg:${WAL_COLOR_0:-#ffffff})\
$time\
[ ](fg:${WAL_COLOR_0:-#ffffff})
"""

add_newline = false

# -------------------------
# USER
# -------------------------
[username]
show_always = true
style_user = "bg:${WAL_COLOR_0:-#444444} fg:${WAL_COLOR_7:-#bbbbbb}"
style_root = "bg:${WAL_COLOR_0:-#444444} fg:${WAL_COLOR_7:-#bbbbbb}"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:${WAL_COLOR_0:-#444444} fg:${WAL_COLOR_7:-#bbbbbb}"
disabled = true

[directory]
style = "bg:${WAL_COLOR_7:-#888888} fg:${WAL_COLOR_0:-#222222}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# -------------------------
# LANGUAGE / ENV SEGMENTS
# -------------------------
[c]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:${WAL_COLOR_15:-#eeeeee} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol $context ]($style)'

# -------------------------
# GIT
# -------------------------
[git_branch]
symbol = ""
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:${WAL_COLOR_15:-#bbbbbb} fg:${WAL_COLOR_0:-#222222}"
format = '[$all_status$ahead_behind ]($style)'

# -------------------------
# TIME
# -------------------------
[time]
time_format = "%R"
style = "bg:${WAL_COLOR_15:-#eeeeee} fg:${WAL_COLOR_0:-#222222}"
format = '[ ⏰ $time ]($style)'
disabled = false
