# ==============================================================================
# Minimal, “prettier” Starship prompt — Pywal16 themed (Arch + Current Dir)
# ==============================================================================
add_newline = true
format = """$os $directory$character"""

# ------------------------------------------------------------------------------
# Arch logo in Pywal blue
# ------------------------------------------------------------------------------
[os]
symbols = { "Arch" = " " }
style = "bold fg:4"   # Pywal color4
format = "[$symbol]($style)"
disabled = false

# ------------------------------------------------------------------------------
# Current directory — shows ~ for home, color5 accent
# ------------------------------------------------------------------------------
[directory]
style = "fg:5"        # soft Pywal accent
format = "[$path]($style)"
truncation_length = 3
home_symbol = "~"
disabled = false

# ------------------------------------------------------------------------------
# Prompt character
# ------------------------------------------------------------------------------
[character]
success_symbol = "[>](fg:7) "
error_symbol   = "[>](fg:9) "

# ------------------------------------------------------------------------------
# Disable unused modules
# ------------------------------------------------------------------------------
[time]
disabled = true

[fill]
disabled = true
