format = """
[](#${STARSHIP_BG1})\
$os\
$username\
[](bg:${STARSHIP_BG1} fg:${STARSHIP_ACC1})\
$directory\
[](fg:${STARSHIP_ACC1} bg:${STARSHIP_ACC2})\
$git_branch\
$git_status\
[](fg:${STARSHIP_ACC2} bg:${STARSHIP_ACC3})\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:${STARSHIP_ACC3} bg:${STARSHIP_ACC1})\
$docker_context\
[](fg:${STARSHIP_ACC1} bg:${STARSHIP_ACC2})\
$time\
[ ](fg:${STARSHIP_FG1})\
"""

add_newline = false

[username]
show_always = true
style_user = "bg:${STARSHIP_BG1} fg:${STARSHIP_FG1}"
style_root = "bg:${STARSHIP_BG1} fg:${STARSHIP_FG1}"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:${STARSHIP_BG1} fg:${STARSHIP_FG1}"
disabled = true

[directory]
style = "bg:${STARSHIP_ACC1} fg:${STARSHIP_BG1}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:${STARSHIP_ACC1} fg:${STARSHIP_BG1}"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:${STARSHIP_ACC2} fg:${STARSHIP_BG1}"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:${STARSHIP_ACC3} fg:${STARSHIP_BG1}"
format = '[ ⏰ $time ]($style)'
