#!/bin/bash
set -euo pipefail

# ===============================
# Variables
# ===============================
USER_NAME="${SUDO_USER:-$USER}"
USER_HOME=$(eval echo "~$USER_NAME")

CONFIG_DIR="$USER_HOME/.config"
WALLPAPERS_DIR="$CONFIG_DIR/assets/wallpapers"
WOFI_CSS="$CONFIG_DIR/wofi/style.css"  # Your Wofi CSS

# ===============================
# Helper functions
# ===============================
print_info()    { echo -e "\033[0;34m[I]\033[0m $1"; }
print_success() { echo -e "\033[0;32m[S]\033[0m $1"; }
print_warning() { echo -e "\033[0;33m[W]\033[0m $1"; }
print_error()   { echo -e "\033[0;31m[E]\033[0m $1"; }

run_as_user() {
    sudo -u "$USER_NAME" bash -c "$1"
}

# ===============================
# Step 1: Select wallpaper
# ===============================
print_info "Selecting wallpaper via Wofi..."
WALL_NAME=$(ls "$WALLPAPERS_DIR" | wofi --prompt "Select Wallpaper:" --dmenu)

if [[ -z "$WALL_NAME" ]]; then
    print_error "No wallpaper selected. Exiting."
    exit 1
fi

WALL_PATH="$WALLPAPERS_DIR/$WALL_NAME"
print_success "Selected wallpaper: $WALL_PATH"

# ===============================
# Step 2: Set wallpaper via swww
# ===============================
print_info "Setting wallpaper via swww..."
swww img "$WALL_PATH" --transition-fps 255 --transition-type outer --transition-duration 0.8
print_success "Wallpaper applied."

# ===============================
# Step 3: Generate Pywal palette
# ===============================
print_info "Generating Pywal colors..."
wal -i "$WALL_PATH" --backend wal
print_success "Pywal colors applied."

# ===============================
# Step 4: Update Wofi CSS from Pywal
# ===============================
if [[ -f "$WOFI_CSS" ]]; then
    print_info "Updating Wofi CSS with Pywal colors..."
    WAL_CACHE="$USER_HOME/.cache/wal/colors.css"

    sed -i -e "s/@background/$(awk -F: '/background/ {gsub(/[ ;]/,"",$2); print $2}' $WAL_CACHE)/" \
           -e "s/@foreground/$(awk -F: '/foreground/ {gsub(/[ ;]/,"",$2); print $2}' $WAL_CACHE)/" \
           -e "s/@color0/$(awk -F: '/color0/ {gsub(/[ ;]/,"",$2); print $2}' $WAL_CACHE)/" \
           -e "s/@color1/$(awk -F: '/color1/ {gsub(/[ ;]/,"",$2); print $2}' $WAL_CACHE)/" \
           "$WOFI_CSS"
    print_success "Wofi CSS updated."
else
    print_warning "Wofi CSS not found at $WOFI_CSS. Please create it manually first."
fi

# ===============================
# Step 5: Configure Starship with Pywal
# ===============================
print_info "Updating Starship prompt with Pywal colors..."
STARSHIP_CONFIG="$CONFIG_DIR/starship.toml"

COLOR_BG=$(awk -F: '/background/ {gsub(/[ ;]/,"",$2); print $2}' "$USER_HOME/.cache/wal/colors.css" | head -1)
COLOR_FG=$(awk -F: '/foreground/ {gsub(/[ ;]/,"",$2); print $2}' "$USER_HOME/.cache/wal/colors.css" | head -1)
COLOR_ACCENT=$(awk -F: '/color1/ {gsub(/[ ;]/,"",$2); print $2}' "$USER_HOME/.cache/wal/colors.css" | head -1)

cat > "$STARSHIP_CONFIG" <<EOF
# Auto-generated by select-wallpaper.sh

[character]
symbol = "❯"
style = "fg=$COLOR_ACCENT"

[username]
style = "fg=$COLOR_ACCENT"

[hostname]
style = "fg=$COLOR_ACCENT"

[directory]
style = "fg=$COLOR_FG"

[git_status]
style = "fg=$COLOR_ACCENT"

[job_summary]
style = "fg=$COLOR_ACCENT"

[package]
style = "fg=$COLOR_ACCENT"

[time]
style = "fg=$COLOR_FG"
EOF

chown "$USER_NAME:$USER_NAME" "$STARSHIP_CONFIG"
print_success "Starship configured with Pywal colors."

# ===============================
# Step 6: Ensure Fastfetch ASCII runs
# ===============================
FASTFETCH_LINE="fastfetch --no-image"
for rc in ".bashrc" ".zshrc"; do
    RC_PATH="$USER_HOME/$rc"
    if [[ -f "$RC_PATH" ]] && ! grep -qF "$FASTFETCH_LINE" "$RC_PATH"; then
        echo -e "\n# Run Fastfetch on terminal start\n$FASTFETCH_LINE" >> "$RC_PATH"
        chown "$USER_NAME:$USER_NAME" "$RC_PATH"
    fi
done
print_success "Fastfetch configured for ASCII output."

print_info "Launching or refreshing Yazi..."
if command -v yazi &>/dev/null; then
    if ! pgrep -x yazi >/dev/null; then
        run_as_user "bash -c 'source $USER_HOME/.cache/wal/colors.sh; env DISPLAY=$DISPLAY XDG_SESSION_TYPE=$XDG_SESSION_TYPE setsid yazi >/dev/null 2>&1 &'"
        print_success "Yazi launched with Pywal colors."
    else
        print_info "Yazi is already running and should auto-refresh colors from Pywal."
    fi
else
    print_warning "Yazi not installed. Install via AUR to enable dynamic Qt file manager theming."
fi

print_success "Wallpaper selection and theming complete!"
