#!/bin/bash
# setwall.sh - Random wallpaper setter + Pywal + Waybar + Yazi + Tofi theming
set -euo pipefail

# ----------------------------
# Directories
# ----------------------------
WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
WAYBAR_CSS="$HOME/.config/waybar/style.css"
PYWAL_CACHE="$HOME/.cache/wal/colors.css"
YAZI_THEME="$HOME/.config/yazi/theme.toml"
TOFI_TEMPLATE="$HOME/.config/tofi/tofi.template"
TOFI_OUTPUT="$HOME/.cache/wal/tofi"

# ----------------------------
# Start swww-daemon if needed
# ----------------------------
if ! pgrep -x "swww-daemon" >/dev/null; then
    echo "Starting swww-daemon..."
    swww-daemon &
    sleep 1
fi

# ----------------------------
# Pick a random wallpaper
# ----------------------------
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" \) | shuf -n 1)
if [[ -z "$WALLPAPER" ]]; then
    echo "No wallpapers found in $WALLPAPER_DIR"
    exit 1
fi

echo "Setting wallpaper: $WALLPAPER"
swww img "$WALLPAPER" --transition-type any --transition-step 90 --transition-fps 60

# ----------------------------
# Generate Pywal colors
# ----------------------------
wal -n -q -i "$WALLPAPER"

# ----------------------------
# Extract colors from Pywal
# ----------------------------
for i in {0..15}; do
    eval COLOR$i=$(grep "color$i" "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
done
BG=$COLOR0
FG=$COLOR7

# ----------------------------
# Write Waybar-compatible CSS
# ----------------------------
mkdir -p "$(dirname "$WAYBAR_CSS")"

cat > "$WAYBAR_CSS" <<EOF
/* Waybar CSS generated by setwall.sh */

/* All 16 Pywal colors */
@define-color color0 ${COLOR0};
@define-color color1 ${COLOR1};
@define-color color2 ${COLOR2};
@define-color color3 ${COLOR3};
@define-color color4 ${COLOR4};
@define-color color5 ${COLOR5};
@define-color color6 ${COLOR6};
@define-color color7 ${COLOR7};
@define-color color8 ${COLOR8};
@define-color color9 ${COLOR9};
@define-color color10 ${COLOR10};
@define-color color11 ${COLOR11};
@define-color color12 ${COLOR12};
@define-color color13 ${COLOR13};
@define-color color14 ${COLOR14};
@define-color color15 ${COLOR15};

* {
    font-family: "JetBrainsMono Nerd Font";
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background-color: transparent;
    color: ${FG};
    transition: background-color 0.5s;
}

.modules-left,
.modules-center,
.modules-right {
    background-color: transparent;
    border-radius: 0;
    margin: 0;
    padding: 0;
}

/* Workspace Dots */

#window,
#clock,
#custom-spotify,
#cpu,
#memory,
#network,
#pulseaudio,
#pulseaudio#microphone,
#custom-power,
#tray {
    background-color: ${BG};
    border-radius: 11.5px;
    margin: 2px;
    padding: 5px 8px;
}

/* Text colors for modules */
#window { color: ${COLOR5}; }
#clock { color: ${COLOR3}; }
#custom-spotify { color: ${COLOR5}; }
#cpu { color: ${COLOR2}; }
#memory { color: ${COLOR4}; }
#network { color: ${COLOR6}; }
#pulseaudio { color: ${COLOR1}; }
#pulseaudio#microphone { color: ${COLOR9}; }
#custom-power { color: ${FG}; }
#tray { color: ${FG}; }
EOF

echo "Waybar colors updated at $WAYBAR_CSS"

# ----------------------------
# Update Yazi Theme
# ----------------------------
mkdir -p "$(dirname "$YAZI_THEME")"

cat > "$YAZI_THEME" <<EOF
[mgr]
fg = "$FG"
bg = "$BG"
border = "$COLOR2"
highlight = "$COLOR4"

[statusbar]
fg = "$FG"
bg = "$BG"

[preview]
fg = "$FG"
bg = "$BG"
EOF

echo "Yazi theme updated at $YAZI_THEME"

# ----------------------------
# Generate Tofi Theme
# ----------------------------
if [[ -f "$TOFI_TEMPLATE" ]]; then
    mkdir -p "$(dirname "$TOFI_OUTPUT")"
    sed -e "s/{color0}/${BG}/g" \
        -e "s/{color4}/${COLOR4}/g" \
        -e "s/{color7}/${FG}/g" \
        -e "s/{color15}/${COLOR15}/g" \
        "$TOFI_TEMPLATE" > "$TOFI_OUTPUT"
    echo "Tofi theme generated at $TOFI_OUTPUT"
else
    echo "Warning: Tofi template not found at $TOFI_TEMPLATE, skipping Tofi theming."
fi

# ----------------------------
# Reload Waybar
# ----------------------------
if pgrep -x "waybar" >/dev/null; then
    echo "Reloading Waybar..."
    pkill -USR2 waybar
else
    echo "Starting Waybar..."
    waybar &
fi

# ----------------------------
# Reload Tofi Automatically
# ----------------------------
if pgrep -x "tofi-drun" >/dev/null; then
    echo "Reloading Tofi with new theme..."
    pkill -x tofi-drun
    tofi-drun -c ~/.cache/wal/tofi --drun-launch=true &
else
    echo "Tofi is not currently running. No reload needed."
fi

echo "Done! Wallpaper, Waybar, Yazi, and Tofi theme updated."
