#!/bin/bash
# setwall.sh - Random wallpaper setter + Pywal + Waybar + Yazi + Tofi theming
set -euo pipefail

# ----------------------------
# Directories
# ----------------------------
WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
WAYBAR_CSS="$HOME/.config/waybar/style.css"
PYWAL_CACHE="$HOME/.cache/wal/colors.css"
YAZI_THEME="$HOME/.config/yazi/theme.toml"
TOFI_TEMPLATE="$HOME/.config/tofi/tofi.template"
TOFI_OUTPUT="$HOME/.cache/wal/tofi"

# ----------------------------
# Start swww-daemon if needed
# ----------------------------
if ! pgrep -x "swww-daemon" >/dev/null; then
    echo "Starting swww-daemon..."
    swww-daemon &
    sleep 1
fi

# ----------------------------
# Pick a random wallpaper
# ----------------------------
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" \) | shuf -n 1)
if [[ -z "$WALLPAPER" ]]; then
    echo "No wallpapers found in "$WALLPAPER_DIR""
    exit 1
fi

echo "Setting wallpaper: $WALLPAPER"
swww img "$WALLPAPER" --transition-type any --transition-step 90 --transition-fps 60

# ----------------------------
# Generate Pywal colors
# ----------------------------
wal -n -q -i "$WALLPAPER"

# ----------------------------
# Extract colors from Pywal
# ----------------------------
BG=$(grep color0 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
FG=$(grep color7 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR0=$(grep color0 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR1=$(grep color1 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR2=$(grep color2 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR3=$(grep color3 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR4=$(grep color4 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR5=$(grep color5 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR6=$(grep color6 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR7=$(grep color7 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR8=$(grep color8 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR9=$(grep color9 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR10=$(grep color10 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR11=$(grep color11 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR12=$(grep color12 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR13=$(grep color13 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR14=$(grep color14 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)
COLOR15=$(grep color15 "$PYWAL_CACHE" | grep -o '#[0-9A-Fa-f]\{6\}' | head -n1)

# ----------------------------
# Write Waybar-compatible CSS
# ----------------------------
mkdir -p "$(dirname "$WAYBAR_CSS")"

cat > "$WAYBAR_CSS" <<EOF
/* This Waybar CSS is dynamically generated by setwall.sh */

/* All 16 Pywal colors as variables */
@define-color color0 ${COLOR0};
@define-color color1 ${COLOR1};
@define-color color2 ${COLOR2};
@define-color color3 ${COLOR3};
@define-color color4 ${COLOR4};
@define-color color5 ${COLOR5};
@define-color color6 ${COLOR6};
@define-color color7 ${COLOR7};
@define-color color8 ${COLOR8};
@define-color color9 ${COLOR9};
@define-color color10 ${COLOR10};
@define-color color11 ${COLOR11};
@define-color color12 ${COLOR12};
@define-color color13 ${COLOR13};
@define-color color14 ${COLOR14};
@define-color color15 ${COLOR15};

* {
    font-family: "JetBrainsMono Nerd Font";
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background-color: transparent;
    color: ${FG};
    transition: background-color 0.5s;
}

/* Make containers transparent to let the modules show their color */
.modules-left,
.modules-center,
.modules-right {
    background-color: transparent;
    border-radius: 0;
    margin: 0;
    padding: 0;
}

/* Individual Module Styles - Pill-shaped with background */
#hyprland-workspaces button {
    background-color: ${BG};
    color: ${FG};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#hyprland-workspaces button.active {
    background-color: ${COLOR1};
    color: ${FG};
}

#hyprland-window {
    background-color: ${BG};
    color: ${FG};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#clock {
    background-color: ${BG};
    color: ${COLOR3};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#custom-spotify {
    background-color: ${BG};
    color: ${COLOR5};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#cpu {
    background-color: ${BG};
    color: ${COLOR2};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#memory {
    background-color: ${BG};
    color: ${COLOR4};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#network {
    background-color: ${BG};
    color: ${COLOR6};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#pulseaudio {
    background-color: ${BG};
    color: ${COLOR1};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#pulseaudio.muted {
    background-color: ${BG};
    color: ${BG};
}

#pulseaudio#microphone {
    background-color: ${BG};
    color: ${COLOR9};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#custom-power {
    background-color: ${BG};
    color: ${FG};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

#tray {
    background-color: ${BG};
    color: ${FG};
    margin: 2px;
    padding: 5px 8px;
    border-radius: 11.5px;
}

/* Hover effects */
#custom-spotify:hover {
    opacity: 0.6;
}

#hyprland-workspaces button:hover {
    opacity: 0.6;
}
EOF

echo "Waybar colors updated at $WAYBAR_CSS"

# ----------------------------
# Update Yazi Theme
# ----------------------------
mkdir -p "$(dirname "$YAZI_THEME")"

cat > "$YAZI_THEME" <<EOF
[mgr]
fg = "$FG"
bg = "$BG"
border = "$COLOR2"
highlight = "$COLOR4"

[statusbar]
fg = "$FG"
bg = "$BG"

[preview]
fg = "$FG"
bg = "$BG"
EOF

echo "Yazi theme updated at $YAZI_THEME"

# ----------------------------
# Generate Tofi Theme
# ----------------------------
if [[ -f "$TOFI_TEMPLATE" ]]; then
    mkdir -p "$(dirname "$TOFI_OUTPUT")"
    
    sed \
        -e "s/{color0}/${BG}/g" \
        -e "s/{color4}/${COLOR4}/g" \
        -e "s/{color7}/${FG}/g" \
        -e "s/{color15}/${COLOR15}/g" \
        "$TOFI_TEMPLATE" > "$TOFI_OUTPUT"

    echo "Tofi theme generated at $TOFI_OUTPUT"
else
    echo "Warning: Tofi template not found at $TOFI_TEMPLATE, skipping Tofi theming."
fi

# ----------------------------
# Reload Waybar
# ----------------------------
if pgrep -x "waybar" >/dev/null; then
    echo "Reloading Waybar..."
    pkill -USR2 waybar
else
    echo "Waybar not running, starting it..."
    waybar &
fi

# ----------------------------
# Reload Tofi Automatically
# ----------------------------
if pgrep -x "tofi-drun" >/dev/null; then
    echo "Reloading Tofi with new theme..."
    pkill -x tofi-drun
    # Relaunch in background if you want it to open immediately
    tofi-drun -c ~/.cache/wal/tofi --drun-launch=true &
else
    echo "Tofi is not currently running. No reload needed."
fi

echo "Done! Wallpaper, Waybar, Yazi, and Tofi theme updated."
