#!/bin/bash

# Changed the hardcoded path to be more portable using the $HOME variable.
# It now correctly points to where your install.sh script copies the assets.
wal -i $(find "$HOME/.config/assets" -type f | shuf -n1)

# Pywal - Hyprland
# Author: SaltyFunnel
# Date: 12/08/2025

# This is a simple script to set the wallpaper on Hyprland using hyprpaper.
# It uses the color scheme generated by Pywal.

# Get the color palette from the pywal cache
source ~/.cache/wal/colors.sh

# Get the wallpaper path from the pywal cache
wallpaper_path=$(cat ~/.cache/wal/wal)

# Hyprpaper Config
hyprpaper_conf="$HOME/.config/hypr/hyprpaper.conf"

# Remove old wallpaper lines from hyprpaper.conf
sed -i '/preload =/d' $hyprpaper_conf
sed -i '/wallpaper =/d' $hyprpaper_conf

# Add new wallpaper lines to hyprpaper.conf
echo "preload = $wallpaper_path" >> $hyprpaper_conf
echo "wallpaper = DP-1, $wallpaper_path" >> $hyprpaper_conf

# Relaunch hyprpaper to apply changes
hyprctl reload
