#!/bin/bash
# ~/.config/theme-wallpaper/hyprland-update.sh
# Dynamically update Hyprland colors from Matugen palette

PALETTE_JSON="$HOME/.config/theme-wallpaper/palette.json"
HYPR_THEME="$HOME/.config/hypr/hypr-colors.conf"

# Extract colors
ACTIVE=$(jq -r '.colors.dark.primary // "#8dcff2"' "$PALETTE_JSON")
INACTIVE=$(jq -r '.colors.dark.secondary // "#b5cad7"' "$PALETTE_JSON")
BACKGROUND=$(jq -r '.colors.dark.background // "#1e1e2e"' "$PALETTE_JSON")

# Strip the "#" so Hyprland accepts RGB format
ACTIVE_RGB="${ACTIVE:1}"
INACTIVE_RGB="${INACTIVE:1}"
BACKGROUND_RGB="${BACKGROUND:1}"

# Write theme to hypr-colors.conf
cat > "$HYPR_THEME" <<EOF
# This file is auto-generated by hyprland-update.sh
general {
    col.active_border = rgb($ACTIVE_RGB)
    col.inactive_border = rgb($INACTIVE_RGB)
}

decoration {
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgb(1e1e2e)
    }
   }
EOF

# Reload Hyprland to apply changes
hyprctl reload
